version: '3.9'
services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: docker/frontend/frontend.dockerfile
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    depends_on:
      - backend

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: docker/backend/backend.dockerfile
    env_file: ".env"
    environment:
      - PYTHONUNBUFFERED=1
      - ENV=production
    restart: unless-stopped
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    container_name: db
    env_file: ".env"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DATABASE}

volumes:
  pgdata:
    driver: local